#!/bin/bash
# $Id: iptkovr,v 1.23 2014/05/23 14:08:24 fulford Exp $
# $Source: /src/merlin/usr/local/etc/RCS/iptkovr,v $
# $Revision: 1.23 $
# Author C W Fulford.
# Copyright 2014 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0709 229 5385
########################################################################
cmd=`basename $0`
fcmd="$@"
syntax="$cmd [-c <config_file>] [-d] [-v] <target>"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$1;shift 2;;
		-d) debug=:;set -x;shift;;
		-v) verbose=:;shift;;
		 *) target=$1;shift;;
	esac
done
config=${config:-"/usr/local/etc/iptkovr.cf"}
[ -f $config ] ||{
	echo "$cmd: can't find $config" >&2
	echo "$cmd: closing down" >&2
	exit 1
}
eval `sed -ne "/$id:/,/^$/{
			/^[ 	][^#]*/p
	}" $config`
id=`id -un`
ok=:
cloneip=`getent hosts $clone|awk '{print $1}'`
targetip=`getent hosts $target|awk '{print $1}'`
txt=07935728612@txtlocal.co.uk

[ $verbose ] && {
	echo "$cmd: monitoring $target on $targetip"  >&2
}
if ping -c 1 $cloneip >/dev/null 2>&1 ;then
	[ $verbose ] && echo "$cmd: $clone at $cloneip on standby">&2
else
	echo "$cmd: standby $clone down - terminating" >&2
	exit 1
fi
while [ $ok ];do
	if ping -c 1 $targetip >/dev/null 2>&1;then
		sleep $sleep
	else
		[ $verbose ] && {
			echo "$cmd: $target not responding on $targetip" >&2
		}
		sleep $sleep
		if ping -c 1 $targetip >/dev/null 2>&1 ;then
		   [ $verbose ]&&{
			echo "$cmd: hiccup only, monitoring $target on $targetip">&2
		   }
		else	
			unset ok		
		fi
	fi
done
msg="$target down - activating $targetip on $clone"

[ $verbose ]&& echo "$cmd: $msg" >&2

logger  -p local0.alert "$msg"

#mailx -s "URGENT $target down" -c $txt $id <<- .
mailx -s "URGENT $target down"  $id <<- .
	$msg
.

ssh -t $cloneip "sudo ifconfig $vif $targetip/24" 2>/dev/null
sleep 3
if ping -c 1 $targetip >/dev/null 2>&1 ;then
	echo "$cmd: ip takeover of $targetip complete"
else
	echo "$cmd: ip takeover of $targetip failed" >&2
fi
[ $verbose ] && echo "$cmd: terminating">&2


